/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexoes;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author berit
 */
public class CriarBD extends javax.swing.JFrame {
    
        final private String driver = "com.mysql.jdbc.Driver";
    Connection conexao;
    private boolean verificacao = false;

    /**
     * Creates new form CriarBD
     */
    public CriarBD() {
        initComponents();
                
        if(verificacao == false) {
        lerConfiguracaoGravada();    
        } 
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        btnSalvarConfiguracao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Host");

        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        jLabel2.setText("Port");

        jLabel3.setText("User");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        pswPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswPasswordActionPerformed(evt);
            }
        });

        btnSalvarConfiguracao.setText("Salvar Configuração MYSQL");
        btnSalvarConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarConfiguracaoActionPerformed(evt);
            }
        });

        jButton2.setText("Criar Banco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 139, Short.MAX_VALUE))
                                    .addComponent(txtPorta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvarConfiguracao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSalvarConfiguracao)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostActionPerformed

    private void btnSalvarConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarConfiguracaoActionPerformed
        gravarConfiguracao();
    }//GEN-LAST:event_btnSalvarConfiguracaoActionPerformed

    private void pswPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:        
        selecttblVendas();
        inserindoindexcliente();
        criarReferenciaTblCliente();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarConfiguracao;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtPorta;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    
    
    private boolean gravarConfiguracao() {
        boolean grava = false;
        try {
            File diretorio = new File("C:/ConexaoBanco/Configuracao");
            if (!diretorio.exists()) {
                diretorio.mkdirs();
            }
            FileWriter arq1 = new FileWriter("C:/ConexaoBanco/Configuracao/conexao.ini");
            PrintWriter gravarArq = new PrintWriter(arq1);
            gravarArq.println(txtHost.getText());
            gravarArq.println(txtPorta.getText());
            gravarArq.println(txtUser.getText());
            gravarArq.println(pswPassword.getPassword());
            arq1.close();
            grava = true;
        } catch (IOException erro) {
            JOptionPane.showMessageDialog(null, "Você nao tem permição de adminstrador para configurar o"
                    + " Sistema.", "ERRO !", 0);
        }
        return grava;        
    }

    private boolean lerConfiguracaoGravada() {
        
             
        boolean leitura = false;
        try {
            String linha;
            String ArquivoConfiguracao = "C:/ConexaoBanco/Configuracao/conexao.ini";
            int cont = 0;
            File arq = new File(ArquivoConfiguracao);
            if (arq.exists()) {

                FileReader reader = new FileReader(ArquivoConfiguracao);
                BufferedReader leitor = new BufferedReader(reader);
                while (true) {
                    linha = leitor.readLine();
                    if (cont == 0) {
                        txtHost.setText(linha);
                    }
                    if (cont == 1) {
                        txtPorta.setText(linha);
                    }
                    if (cont == 2) {
                        txtUser.setText(linha);
                    }
                    if (cont >= 3) {
                        pswPassword.setText(linha);
                        String conteudoPassword = new String(pswPassword.getPassword());
                        conteudoPassword.toString();
                        break;
                    }
                    System.out.println(linha + "\n");
                    cont++;
                }
            }
            if (arq.exists()) {
                
                if (conexaoServidor(txtHost.getText(), txtPorta.getText(), txtUser.getText(), pswPassword.getPassword().toString())) {
                    leitura = true;
                }
            }

        } catch (Exception erro) {
        }

        return leitura;
    }
    
    private boolean conexaoServidor(String pServidor, String pPorta, String pUsuario, String pSenha) {
        boolean con = false;
        String servidor = pServidor;
        String portaConexao = pPorta;
        String usuario = pUsuario;
        String senha = pSenha;
        try {
            Class.forName(driver);
            conexao = DriverManager.getConnection("jdbc:mysql://" + servidor + ":" + portaConexao + "",
                    usuario, senha);
            con = true;
        } catch (ClassNotFoundException Fonte) {
            JOptionPane.showMessageDialog(null, "Driver nao localizado");
        } catch (SQLException Fonte) {
        }
        return con;
    }
    
    private boolean conexaoDataBase(String pServidor, String pPorta, String pUsuario, String pSenha) {
    boolean con = false;
    String servidor = pServidor;
    String portaConexao = pPorta;
    String usuario = pUsuario;
    String senha = pSenha;
    try {
        Class.forName(driver);
        conexao = DriverManager.getConnection("jdbc:mysql://" + servidor + ":" + portaConexao
                + "/bd_Brt_Vendas", usuario, senha);
        con = true;
    } catch (ClassNotFoundException Fonte) {
        JOptionPane.showMessageDialog(null, "Driver nao localizado");
    } catch (SQLException Fonte) {
    }
    return con;
}

    private void fechaConexao() {
        try {
            conexao.close();
        } catch (SQLException fech) {
            JOptionPane.showMessageDialog(null, "Erro ao fechar conexao com o banco de dados" + fech);
        }
    }
    
    private boolean criaDataBaseCompleto() {
        boolean sucesso = true;
        if (criaBanco() == false) {
            sucesso = false;
        } else if (criaTabelas() == false) {
            sucesso = false;
        }

        return sucesso;
    }

    private boolean criaBanco() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "CREATE DATABASE IF NOT EXISTS bd_Brt_Vendas CHARACTER SET utf8 COLLATE utf8_general_ci";

        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
    //        FECHA_CONEXAO();
        return sucesso;
    }
    
    private boolean criaTabelas() {
        boolean sucesso = true;

        conexaoDataBase(txtHost.getText(), txtPorta.getText(), txtUser.getText(), pswPassword.getPassword().toString());

        if (criaTabelatblcliente() == false) {
            sucesso = false;
        } else if (criarTabelatblusuario() == false) {
            sucesso = false;
        } else if (criarTabelatblproduto() == false) {
            sucesso = false;
        } else if (criarTabelatblvendas() == false) {
            sucesso = false;
        } else if (criarTabelatblvendasprodutos() == false) {
            sucesso = false;
        }

        fechaConexao();
        return sucesso;
    }    
    
    private boolean criaTabelatblcliente() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "CREATE TABLE  IF NOT EXISTS tbl_cliente ("
            + " pk_id_cliente BIGINT NOT NULL AUTO_INCREMENT ,"
            + " cli_nome VARCHAR( 300 ) NOT NULL ,"
            + " cli_endereco VARCHAR( 350 ) NOT NULL ,"
            + " cli_bairro VARCHAR( 300 ) NOT NULL ,"
            + " cli_cidade VARCHAR( 200 ) NOT NULL ,"
            + " cli_uf VARCHAR( 2 ) NOT NULL ,"
            + " cli_cep VARCHAR( 9 ) NOT NULL ,"
            + " cli_telefone VARCHAR( 15 ) NULL ,"
            + " PRIMARY KEY ( pk_id_cliente ) "
            + " ) ENGINE = InnoDB";
                
        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
    
        private boolean criarTabelatblusuario() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "CREATE TABLE  IF NOT EXISTS tbl_usuario ("
            + " pk_id_usuario BIGINT NOT NULL AUTO_INCREMENT ,"
            + " usu_nome VARCHAR( 150 ) NOT NULL ,"
            + " usu_login VARCHAR( 350 ) NOT NULL ,"
            + " usu_senha VARCHAR( 20 ) NOT NULL ,"
            + " PRIMARY KEY ( pk_id_usuario ) "
            + " ) ENGINE = InnoDB";

        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
        
    private boolean criarTabelatblproduto() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "CREATE TABLE  IF NOT EXISTS tbl_produto ("
            + " pk_id_produto BIGINT NOT NULL AUTO_INCREMENT ,"
            + " pro_nome VARCHAR( 300 ) NOT NULL ,"
            + " pro_valor DOUBLE NOT NULL ,"
            + " pro_estoque INT NOT NULL ,"
            + " PRIMARY KEY ( pk_id_produto ) "
            + " ) ENGINE = InnoDB";
        
        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
    
        private boolean criarTabelatblvendas() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "CREATE TABLE  IF NOT EXISTS tbl_vendas ("
                + " pk_id_vendas BIGINT NOT NULL AUTO_INCREMENT ,"
                + " fk_cliente BIGINT UNSIGNED NOT NULL , "
                + " ven_data_venda DATE NOT NULL , "
                + " ven_valor_liquido DOUBLE NOT NULL , "
                + " ven_valor_bruto DOUBLE NOT NULL , "
                + " ven_desconto DOUBLE NOT NULL , "              
                + " PRIMARY KEY ( pk_id_vendas )"
                + " ) ENGINE = InnoDB";
        
               //+ " ADD INDEX fkcliente ( fk_cliente ), "
                /*ALTER TABLE `db_concessionaria`.`tbl_vendas` ADD INDEX `fkcliente` (`fk_cliente`);*/
                //+ " FOREIGN KEY ( fk_cliente ) REFERENCES tbl_cliente( pk_id_cliente ) ON DELETE RESTRICT ON UPDATE RESTRICT,"
        

        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
                
        
    private boolean criarTabelatblvendasprodutos() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "CREATE TABLE  IF NOT EXISTS tbl_vendas_produtos ("
            + " pk_id_venda_produto BIGINT NOT NULL AUTO_INCREMENT ,"
            + " fk_produto BIGINT UNSIGNED NOT NULL , "
            + " fk_vendas BIGINT UNSIGNED NOT NULL , "
            + " ven_pro_valor DOUBLE NOT NULL , "
            + " ven_pro_quantidade INT NOT NULL , "
            + " PRIMARY KEY ( pk_id_venda_produto ), "
            + " ) ENGINE = InnoDB";
        /*ALTER TABLE `db_concessionaria`.`tbl_vendas_produtos` ADD INDEX `fkprodutos` (`fk_produto`);
        //ALTER TABLE `db_concessionaria`.`tbl_vendas_produtos` ADD INDEX `fkvendas` (`fk_vendas`);*/
        //+ " FOREIGN KEY (fk_produto) REFERENCES tbl_cliente(pk_id_produto) ON DELETE RESTRICT ON UPDATE RESTRICT,"
        //+ " FOREIGN KEY (fk_vendas) REFERENCES tbl_vendas(pk_id_vendas) ON DELETE RESTRICT ON UPDATE RESTRICT"

        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
    
        private boolean selecttblVendas() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "SELECT * FROM tbl_vendas ";
        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
        
    private boolean inserindoindexcliente() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "ALTER TABLE tbl_vendas ADD INDEX fkcliente ( fk_cliente )";
        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
    
    private boolean criarReferenciaTblCliente() {
        boolean sucesso = false;
        PreparedStatement stm;
        String sql = "ALTER TABLE tbl_vendas ADD FOREIGN KEY (fk_cliente) REFERENCES tbl_cliente ( pk_id_cliente ) ON DELETE RESTRICT ON UPDATE RESTRICT";
        try {
            stm = conexao.prepareStatement(sql);
            stm.execute();
            sucesso = true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", 0);
        }
        return sucesso;
    }
    

  
        

    
}


